USE qltl_luat_dan_su;
SET NAMES utf8mb4;

-- Danh muc/linh vuc phap ly, tranh trung theo DM_ten.
INSERT INTO DANH_MUC (DM_ten) VALUES ('Bộ luật Dân sự') ON DUPLICATE KEY UPDATE DM_ten = VALUES(DM_ten);
INSERT INTO DANH_MUC (DM_ten) VALUES ('Luật Hôn nhân và Gia đình') ON DUPLICATE KEY UPDATE DM_ten = VALUES(DM_ten);
INSERT INTO DANH_MUC (DM_ten) VALUES ('Luật Đất đai') ON DUPLICATE KEY UPDATE DM_ten = VALUES(DM_ten);
INSERT INTO DANH_MUC (DM_ten) VALUES ('Luật Lao động') ON DUPLICATE KEY UPDATE DM_ten = VALUES(DM_ten);

-- Loai tai lieu phap ly, tranh trung theo LTLPL_ten.
INSERT INTO LOAI_TAI_LIEU_PHAP_LY (LTLPL_ten) VALUES ('Bộ luật') ON DUPLICATE KEY UPDATE LTLPL_ten = VALUES(LTLPL_ten);
INSERT INTO LOAI_TAI_LIEU_PHAP_LY (LTLPL_ten) VALUES ('Nghị định') ON DUPLICATE KEY UPDATE LTLPL_ten = VALUES(LTLPL_ten);
INSERT INTO LOAI_TAI_LIEU_PHAP_LY (LTLPL_ten) VALUES ('Nghị quyết') ON DUPLICATE KEY UPDATE LTLPL_ten = VALUES(LTLPL_ten);
INSERT INTO LOAI_TAI_LIEU_PHAP_LY (LTLPL_ten) VALUES ('Luật') ON DUPLICATE KEY UPDATE LTLPL_ten = VALUES(LTLPL_ten);
INSERT INTO LOAI_TAI_LIEU_PHAP_LY (LTLPL_ten) VALUES ('Thông tư liên tịch') ON DUPLICATE KEY UPDATE LTLPL_ten = VALUES(LTLPL_ten);
INSERT INTO LOAI_TAI_LIEU_PHAP_LY (LTLPL_ten) VALUES ('Thông tư') ON DUPLICATE KEY UPDATE LTLPL_ten = VALUES(LTLPL_ten);

-- Tai lieu phap ly da crawl, tranh trung theo (TL_soHieu, TL_ten).
INSERT INTO TAI_LIEU (DM_id, LTLPL_id, TL_ten, TL_duongDan, TL_dinhDang, TL_nguoiTao, TL_ngayTao, TL_ngayBanHanh, TL_daXoa, TL_baoMat, TL_soHieu) VALUES ((SELECT DM_id FROM DANH_MUC WHERE DM_ten = 'Bộ luật Dân sự' LIMIT 1), (SELECT LTLPL_id FROM LOAI_TAI_LIEU_PHAP_LY WHERE LTLPL_ten = 'Bộ luật' LIMIT 1), 'Bộ luật Dân sự 2015', 'documents/dan-su/bo-luat-dan-su-2015.docx', 'docx', 'crawler', NOW(), '2015-11-24', FALSE, 'NOI_BO', '91/2015/QH13') ON DUPLICATE KEY UPDATE DM_id = VALUES(DM_id), LTLPL_id = VALUES(LTLPL_id), TL_duongDan = VALUES(TL_duongDan), TL_dinhDang = VALUES(TL_dinhDang), TL_ngayBanHanh = VALUES(TL_ngayBanHanh), TL_daXoa = VALUES(TL_daXoa);
INSERT INTO TAI_LIEU (DM_id, LTLPL_id, TL_ten, TL_duongDan, TL_dinhDang, TL_nguoiTao, TL_ngayTao, TL_ngayBanHanh, TL_daXoa, TL_baoMat, TL_soHieu) VALUES ((SELECT DM_id FROM DANH_MUC WHERE DM_ten = 'Bộ luật Dân sự' LIMIT 1), (SELECT LTLPL_id FROM LOAI_TAI_LIEU_PHAP_LY WHERE LTLPL_ten = 'Nghị định' LIMIT 1), 'Nghị định 21/2021/NĐ-CP hướng dẫn Bộ luật Dân sự về bảo đảm thực hiện nghĩa vụ', 'documents/dan-su/nghi-đinh-212021nđ-cp-huong-dan-bo-luat-dan-su-ve-bao-đam-thuc-hien-nghia-vu.docx', 'docx', 'crawler', NOW(), '2021-03-19', FALSE, 'NOI_BO', '21/2021/NĐ-CP') ON DUPLICATE KEY UPDATE DM_id = VALUES(DM_id), LTLPL_id = VALUES(LTLPL_id), TL_duongDan = VALUES(TL_duongDan), TL_dinhDang = VALUES(TL_dinhDang), TL_ngayBanHanh = VALUES(TL_ngayBanHanh), TL_daXoa = VALUES(TL_daXoa);
INSERT INTO TAI_LIEU (DM_id, LTLPL_id, TL_ten, TL_duongDan, TL_dinhDang, TL_nguoiTao, TL_ngayTao, TL_ngayBanHanh, TL_daXoa, TL_baoMat, TL_soHieu) VALUES ((SELECT DM_id FROM DANH_MUC WHERE DM_ten = 'Bộ luật Dân sự' LIMIT 1), (SELECT LTLPL_id FROM LOAI_TAI_LIEU_PHAP_LY WHERE LTLPL_ten = 'Nghị định' LIMIT 1), 'Nghị định 22/2025/NĐ-CP về giao dịch điện tử trong lĩnh vực dân sự', 'documents/dan-su/nghi-đinh-222025nđ-cp-ve-giao-dich-đien-tu-trong-linh-vuc-dan-su.docx', 'docx', 'crawler', NOW(), '2025-01-10', FALSE, 'NOI_BO', '22/2025/NĐ-CP') ON DUPLICATE KEY UPDATE DM_id = VALUES(DM_id), LTLPL_id = VALUES(LTLPL_id), TL_duongDan = VALUES(TL_duongDan), TL_dinhDang = VALUES(TL_dinhDang), TL_ngayBanHanh = VALUES(TL_ngayBanHanh), TL_daXoa = VALUES(TL_daXoa);
INSERT INTO TAI_LIEU (DM_id, LTLPL_id, TL_ten, TL_duongDan, TL_dinhDang, TL_nguoiTao, TL_ngayTao, TL_ngayBanHanh, TL_daXoa, TL_baoMat, TL_soHieu) VALUES ((SELECT DM_id FROM DANH_MUC WHERE DM_ten = 'Bộ luật Dân sự' LIMIT 1), (SELECT LTLPL_id FROM LOAI_TAI_LIEU_PHAP_LY WHERE LTLPL_ten = 'Nghị quyết' LIMIT 1), 'Nghị quyết 04/2017/NQ-HĐTP hướng dẫn áp dụng một số quy định tại Bộ luật Dân sự', 'documents/dan-su/nghi-quyet-042017nq-hđtp-huong-dan-ap-dung-mot-so-quy-đinh-tai-bo-luat-dan-su.docx', 'docx', 'crawler', NOW(), '2017-05-05', FALSE, 'NOI_BO', '04/2017/NQ-HĐTP') ON DUPLICATE KEY UPDATE DM_id = VALUES(DM_id), LTLPL_id = VALUES(LTLPL_id), TL_duongDan = VALUES(TL_duongDan), TL_dinhDang = VALUES(TL_dinhDang), TL_ngayBanHanh = VALUES(TL_ngayBanHanh), TL_daXoa = VALUES(TL_daXoa);
INSERT INTO TAI_LIEU (DM_id, LTLPL_id, TL_ten, TL_duongDan, TL_dinhDang, TL_nguoiTao, TL_ngayTao, TL_ngayBanHanh, TL_daXoa, TL_baoMat, TL_soHieu) VALUES ((SELECT DM_id FROM DANH_MUC WHERE DM_ten = 'Bộ luật Dân sự' LIMIT 1), (SELECT LTLPL_id FROM LOAI_TAI_LIEU_PHAP_LY WHERE LTLPL_ten = 'Nghị định' LIMIT 1), 'Nghị định 48/2024/NĐ-CP sửa đổi Nghị định về đăng ký biện pháp bảo đảm', 'documents/dan-su/nghi-đinh-482024nđ-cp-sua-đoi-nghi-đinh-ve-đang-ky-bien-phap-bao-đam.docx', 'docx', 'crawler', NOW(), '2024-05-09', FALSE, 'NOI_BO', '48/2024/NĐ-CP') ON DUPLICATE KEY UPDATE DM_id = VALUES(DM_id), LTLPL_id = VALUES(LTLPL_id), TL_duongDan = VALUES(TL_duongDan), TL_dinhDang = VALUES(TL_dinhDang), TL_ngayBanHanh = VALUES(TL_ngayBanHanh), TL_daXoa = VALUES(TL_daXoa);
INSERT INTO TAI_LIEU (DM_id, LTLPL_id, TL_ten, TL_duongDan, TL_dinhDang, TL_nguoiTao, TL_ngayTao, TL_ngayBanHanh, TL_daXoa, TL_baoMat, TL_soHieu) VALUES ((SELECT DM_id FROM DANH_MUC WHERE DM_ten = 'Luật Hôn nhân và Gia đình' LIMIT 1), (SELECT LTLPL_id FROM LOAI_TAI_LIEU_PHAP_LY WHERE LTLPL_ten = 'Luật' LIMIT 1), 'Luật Hôn nhân và Gia đình 2014', 'documents/hon-nhan-gia-dinh/luat-hon-nhan-va-gia-đinh-2014.docx', 'docx', 'crawler', NOW(), '2014-06-19', FALSE, 'NOI_BO', '52/2014/QH13') ON DUPLICATE KEY UPDATE DM_id = VALUES(DM_id), LTLPL_id = VALUES(LTLPL_id), TL_duongDan = VALUES(TL_duongDan), TL_dinhDang = VALUES(TL_dinhDang), TL_ngayBanHanh = VALUES(TL_ngayBanHanh), TL_daXoa = VALUES(TL_daXoa);
INSERT INTO TAI_LIEU (DM_id, LTLPL_id, TL_ten, TL_duongDan, TL_dinhDang, TL_nguoiTao, TL_ngayTao, TL_ngayBanHanh, TL_daXoa, TL_baoMat, TL_soHieu) VALUES ((SELECT DM_id FROM DANH_MUC WHERE DM_ten = 'Luật Hôn nhân và Gia đình' LIMIT 1), (SELECT LTLPL_id FROM LOAI_TAI_LIEU_PHAP_LY WHERE LTLPL_ten = 'Nghị định' LIMIT 1), 'Nghị định 126/2014/NĐ-CP hướng dẫn Luật Hôn nhân và Gia đình', 'documents/hon-nhan-gia-dinh/nghi-đinh-1262014nđ-cp-huong-dan-luat-hon-nhan-va-gia-đinh.docx', 'docx', 'crawler', NOW(), '2014-12-31', FALSE, 'NOI_BO', '126/2014/NĐ-CP') ON DUPLICATE KEY UPDATE DM_id = VALUES(DM_id), LTLPL_id = VALUES(LTLPL_id), TL_duongDan = VALUES(TL_duongDan), TL_dinhDang = VALUES(TL_dinhDang), TL_ngayBanHanh = VALUES(TL_ngayBanHanh), TL_daXoa = VALUES(TL_daXoa);
INSERT INTO TAI_LIEU (DM_id, LTLPL_id, TL_ten, TL_duongDan, TL_dinhDang, TL_nguoiTao, TL_ngayTao, TL_ngayBanHanh, TL_daXoa, TL_baoMat, TL_soHieu) VALUES ((SELECT DM_id FROM DANH_MUC WHERE DM_ten = 'Luật Hôn nhân và Gia đình' LIMIT 1), (SELECT LTLPL_id FROM LOAI_TAI_LIEU_PHAP_LY WHERE LTLPL_ten = 'Nghị định' LIMIT 1), 'Nghị định 10/2015/NĐ-CP quy định về sinh con bằng kỹ thuật thụ tinh trong ống nghiệm', 'documents/hon-nhan-gia-dinh/nghi-đinh-102015nđ-cp-quy-đinh-ve-sinh-con-bang-ky-thuat-thu-tinh-trong-ong-nghi.docx', 'docx', 'crawler', NOW(), '2015-01-28', FALSE, 'NOI_BO', '10/2015/NĐ-CP') ON DUPLICATE KEY UPDATE DM_id = VALUES(DM_id), LTLPL_id = VALUES(LTLPL_id), TL_duongDan = VALUES(TL_duongDan), TL_dinhDang = VALUES(TL_dinhDang), TL_ngayBanHanh = VALUES(TL_ngayBanHanh), TL_daXoa = VALUES(TL_daXoa);
INSERT INTO TAI_LIEU (DM_id, LTLPL_id, TL_ten, TL_duongDan, TL_dinhDang, TL_nguoiTao, TL_ngayTao, TL_ngayBanHanh, TL_daXoa, TL_baoMat, TL_soHieu) VALUES ((SELECT DM_id FROM DANH_MUC WHERE DM_ten = 'Luật Hôn nhân và Gia đình' LIMIT 1), (SELECT LTLPL_id FROM LOAI_TAI_LIEU_PHAP_LY WHERE LTLPL_ten = 'Thông tư liên tịch' LIMIT 1), 'Thông tư liên tịch 01/2016/TTLT-TANDTC-VKSNDTC-BTP hướng dẫn thi hành Luật HNGĐ', 'documents/hon-nhan-gia-dinh/thong-tu-lien-tich-012016ttlt-tandtc-vksndtc-btp-huong-dan-thi-hanh-luat-hngđ.docx', 'docx', 'crawler', NOW(), '2016-01-06', FALSE, 'NOI_BO', '01/2016/TTLT-TANDTC-VKSNDTC-BTP') ON DUPLICATE KEY UPDATE DM_id = VALUES(DM_id), LTLPL_id = VALUES(LTLPL_id), TL_duongDan = VALUES(TL_duongDan), TL_dinhDang = VALUES(TL_dinhDang), TL_ngayBanHanh = VALUES(TL_ngayBanHanh), TL_daXoa = VALUES(TL_daXoa);
INSERT INTO TAI_LIEU (DM_id, LTLPL_id, TL_ten, TL_duongDan, TL_dinhDang, TL_nguoiTao, TL_ngayTao, TL_ngayBanHanh, TL_daXoa, TL_baoMat, TL_soHieu) VALUES ((SELECT DM_id FROM DANH_MUC WHERE DM_ten = 'Luật Hôn nhân và Gia đình' LIMIT 1), (SELECT LTLPL_id FROM LOAI_TAI_LIEU_PHAP_LY WHERE LTLPL_ten = 'Luật' LIMIT 1), 'Luật Phòng, chống bạo lực gia đình 2022', 'documents/hon-nhan-gia-dinh/luat-phong-chong-bao-luc-gia-đinh-2022.docx', 'docx', 'crawler', NOW(), '2022-11-14', FALSE, 'NOI_BO', '13/2022/QH15') ON DUPLICATE KEY UPDATE DM_id = VALUES(DM_id), LTLPL_id = VALUES(LTLPL_id), TL_duongDan = VALUES(TL_duongDan), TL_dinhDang = VALUES(TL_dinhDang), TL_ngayBanHanh = VALUES(TL_ngayBanHanh), TL_daXoa = VALUES(TL_daXoa);
INSERT INTO TAI_LIEU (DM_id, LTLPL_id, TL_ten, TL_duongDan, TL_dinhDang, TL_nguoiTao, TL_ngayTao, TL_ngayBanHanh, TL_daXoa, TL_baoMat, TL_soHieu) VALUES ((SELECT DM_id FROM DANH_MUC WHERE DM_ten = 'Luật Đất đai' LIMIT 1), (SELECT LTLPL_id FROM LOAI_TAI_LIEU_PHAP_LY WHERE LTLPL_ten = 'Luật' LIMIT 1), 'Luật Đất đai 2024', 'documents/dat-dai/luat-đat-đai-2024.docx', 'docx', 'crawler', NOW(), '2024-01-18', FALSE, 'NOI_BO', '31/2024/QH15') ON DUPLICATE KEY UPDATE DM_id = VALUES(DM_id), LTLPL_id = VALUES(LTLPL_id), TL_duongDan = VALUES(TL_duongDan), TL_dinhDang = VALUES(TL_dinhDang), TL_ngayBanHanh = VALUES(TL_ngayBanHanh), TL_daXoa = VALUES(TL_daXoa);
INSERT INTO TAI_LIEU (DM_id, LTLPL_id, TL_ten, TL_duongDan, TL_dinhDang, TL_nguoiTao, TL_ngayTao, TL_ngayBanHanh, TL_daXoa, TL_baoMat, TL_soHieu) VALUES ((SELECT DM_id FROM DANH_MUC WHERE DM_ten = 'Luật Đất đai' LIMIT 1), (SELECT LTLPL_id FROM LOAI_TAI_LIEU_PHAP_LY WHERE LTLPL_ten = 'Nghị định' LIMIT 1), 'Nghị định 71/2024/NĐ-CP quy định về giá đất', 'documents/dat-dai/nghi-đinh-712024nđ-cp-quy-đinh-ve-gia-đat.docx', 'docx', 'crawler', NOW(), '2024-06-27', FALSE, 'NOI_BO', '71/2024/NĐ-CP') ON DUPLICATE KEY UPDATE DM_id = VALUES(DM_id), LTLPL_id = VALUES(LTLPL_id), TL_duongDan = VALUES(TL_duongDan), TL_dinhDang = VALUES(TL_dinhDang), TL_ngayBanHanh = VALUES(TL_ngayBanHanh), TL_daXoa = VALUES(TL_daXoa);
INSERT INTO TAI_LIEU (DM_id, LTLPL_id, TL_ten, TL_duongDan, TL_dinhDang, TL_nguoiTao, TL_ngayTao, TL_ngayBanHanh, TL_daXoa, TL_baoMat, TL_soHieu) VALUES ((SELECT DM_id FROM DANH_MUC WHERE DM_ten = 'Luật Đất đai' LIMIT 1), (SELECT LTLPL_id FROM LOAI_TAI_LIEU_PHAP_LY WHERE LTLPL_ten = 'Nghị định' LIMIT 1), 'Nghị định 102/2024/NĐ-CP hướng dẫn Luật Đất đai 2024', 'documents/dat-dai/nghi-đinh-1022024nđ-cp-huong-dan-luat-đat-đai-2024.docx', 'docx', 'crawler', NOW(), '2024-07-30', FALSE, 'NOI_BO', '102/2024/NĐ-CP') ON DUPLICATE KEY UPDATE DM_id = VALUES(DM_id), LTLPL_id = VALUES(LTLPL_id), TL_duongDan = VALUES(TL_duongDan), TL_dinhDang = VALUES(TL_dinhDang), TL_ngayBanHanh = VALUES(TL_ngayBanHanh), TL_daXoa = VALUES(TL_daXoa);
INSERT INTO TAI_LIEU (DM_id, LTLPL_id, TL_ten, TL_duongDan, TL_dinhDang, TL_nguoiTao, TL_ngayTao, TL_ngayBanHanh, TL_daXoa, TL_baoMat, TL_soHieu) VALUES ((SELECT DM_id FROM DANH_MUC WHERE DM_ten = 'Luật Đất đai' LIMIT 1), (SELECT LTLPL_id FROM LOAI_TAI_LIEU_PHAP_LY WHERE LTLPL_ten = 'Nghị định' LIMIT 1), 'Nghị định 101/2024/NĐ-CP về đăng ký đất đai, cấp Giấy chứng nhận', 'documents/dat-dai/nghi-đinh-1012024nđ-cp-ve-đang-ky-đat-đai-cap-giay-chung-nhan.docx', 'docx', 'crawler', NOW(), '2024-07-29', FALSE, 'NOI_BO', '101/2024/NĐ-CP') ON DUPLICATE KEY UPDATE DM_id = VALUES(DM_id), LTLPL_id = VALUES(LTLPL_id), TL_duongDan = VALUES(TL_duongDan), TL_dinhDang = VALUES(TL_dinhDang), TL_ngayBanHanh = VALUES(TL_ngayBanHanh), TL_daXoa = VALUES(TL_daXoa);
INSERT INTO TAI_LIEU (DM_id, LTLPL_id, TL_ten, TL_duongDan, TL_dinhDang, TL_nguoiTao, TL_ngayTao, TL_ngayBanHanh, TL_daXoa, TL_baoMat, TL_soHieu) VALUES ((SELECT DM_id FROM DANH_MUC WHERE DM_ten = 'Luật Đất đai' LIMIT 1), (SELECT LTLPL_id FROM LOAI_TAI_LIEU_PHAP_LY WHERE LTLPL_ten = 'Thông tư' LIMIT 1), 'Thông tư 02/2024/TT-BTNMT quy định kỹ thuật điều tra, đánh giá đất đai', 'documents/dat-dai/thong-tu-022024tt-btnmt-quy-đinh-ky-thuat-đieu-tra-đanh-gia-đat-đai.docx', 'docx', 'crawler', NOW(), '2024-04-15', FALSE, 'NOI_BO', '02/2024/TT-BTNMT') ON DUPLICATE KEY UPDATE DM_id = VALUES(DM_id), LTLPL_id = VALUES(LTLPL_id), TL_duongDan = VALUES(TL_duongDan), TL_dinhDang = VALUES(TL_dinhDang), TL_ngayBanHanh = VALUES(TL_ngayBanHanh), TL_daXoa = VALUES(TL_daXoa);
INSERT INTO TAI_LIEU (DM_id, LTLPL_id, TL_ten, TL_duongDan, TL_dinhDang, TL_nguoiTao, TL_ngayTao, TL_ngayBanHanh, TL_daXoa, TL_baoMat, TL_soHieu) VALUES ((SELECT DM_id FROM DANH_MUC WHERE DM_ten = 'Luật Lao động' LIMIT 1), (SELECT LTLPL_id FROM LOAI_TAI_LIEU_PHAP_LY WHERE LTLPL_ten = 'Bộ luật' LIMIT 1), 'Bộ luật Lao động 2019', 'documents/lao-dong/bo-luat-lao-đong-2019.docx', 'docx', 'crawler', NOW(), '2019-11-20', FALSE, 'NOI_BO', '45/2019/QH14') ON DUPLICATE KEY UPDATE DM_id = VALUES(DM_id), LTLPL_id = VALUES(LTLPL_id), TL_duongDan = VALUES(TL_duongDan), TL_dinhDang = VALUES(TL_dinhDang), TL_ngayBanHanh = VALUES(TL_ngayBanHanh), TL_daXoa = VALUES(TL_daXoa);
INSERT INTO TAI_LIEU (DM_id, LTLPL_id, TL_ten, TL_duongDan, TL_dinhDang, TL_nguoiTao, TL_ngayTao, TL_ngayBanHanh, TL_daXoa, TL_baoMat, TL_soHieu) VALUES ((SELECT DM_id FROM DANH_MUC WHERE DM_ten = 'Luật Lao động' LIMIT 1), (SELECT LTLPL_id FROM LOAI_TAI_LIEU_PHAP_LY WHERE LTLPL_ten = 'Nghị định' LIMIT 1), 'Nghị định 145/2020/NĐ-CP hướng dẫn Bộ luật Lao động về điều kiện lao động', 'documents/lao-dong/nghi-đinh-1452020nđ-cp-huong-dan-bo-luat-lao-đong-ve-đieu-kien-lao-đong.docx', 'docx', 'crawler', NOW(), '2020-12-14', FALSE, 'NOI_BO', '145/2020/NĐ-CP') ON DUPLICATE KEY UPDATE DM_id = VALUES(DM_id), LTLPL_id = VALUES(LTLPL_id), TL_duongDan = VALUES(TL_duongDan), TL_dinhDang = VALUES(TL_dinhDang), TL_ngayBanHanh = VALUES(TL_ngayBanHanh), TL_daXoa = VALUES(TL_daXoa);
INSERT INTO TAI_LIEU (DM_id, LTLPL_id, TL_ten, TL_duongDan, TL_dinhDang, TL_nguoiTao, TL_ngayTao, TL_ngayBanHanh, TL_daXoa, TL_baoMat, TL_soHieu) VALUES ((SELECT DM_id FROM DANH_MUC WHERE DM_ten = 'Luật Lao động' LIMIT 1), (SELECT LTLPL_id FROM LOAI_TAI_LIEU_PHAP_LY WHERE LTLPL_ten = 'Nghị định' LIMIT 1), 'Nghị định 12/2022/NĐ-CP quy định xử phạt vi phạm hành chính trong lĩnh vực lao động', 'documents/lao-dong/nghi-đinh-122022nđ-cp-quy-đinh-xu-phat-vi-pham-hanh-chinh-trong-linh-vuc-lao-đon.docx', 'docx', 'crawler', NOW(), '2022-01-17', FALSE, 'NOI_BO', '12/2022/NĐ-CP') ON DUPLICATE KEY UPDATE DM_id = VALUES(DM_id), LTLPL_id = VALUES(LTLPL_id), TL_duongDan = VALUES(TL_duongDan), TL_dinhDang = VALUES(TL_dinhDang), TL_ngayBanHanh = VALUES(TL_ngayBanHanh), TL_daXoa = VALUES(TL_daXoa);
INSERT INTO TAI_LIEU (DM_id, LTLPL_id, TL_ten, TL_duongDan, TL_dinhDang, TL_nguoiTao, TL_ngayTao, TL_ngayBanHanh, TL_daXoa, TL_baoMat, TL_soHieu) VALUES ((SELECT DM_id FROM DANH_MUC WHERE DM_ten = 'Luật Lao động' LIMIT 1), (SELECT LTLPL_id FROM LOAI_TAI_LIEU_PHAP_LY WHERE LTLPL_ten = 'Nghị định' LIMIT 1), 'Nghị định 135/2020/NĐ-CP quy định về tuổi nghỉ hưu', 'documents/lao-dong/nghi-đinh-1352020nđ-cp-quy-đinh-ve-tuoi-nghi-huu.docx', 'docx', 'crawler', NOW(), '2020-11-18', FALSE, 'NOI_BO', '135/2020/NĐ-CP') ON DUPLICATE KEY UPDATE DM_id = VALUES(DM_id), LTLPL_id = VALUES(LTLPL_id), TL_duongDan = VALUES(TL_duongDan), TL_dinhDang = VALUES(TL_dinhDang), TL_ngayBanHanh = VALUES(TL_ngayBanHanh), TL_daXoa = VALUES(TL_daXoa);
INSERT INTO TAI_LIEU (DM_id, LTLPL_id, TL_ten, TL_duongDan, TL_dinhDang, TL_nguoiTao, TL_ngayTao, TL_ngayBanHanh, TL_daXoa, TL_baoMat, TL_soHieu) VALUES ((SELECT DM_id FROM DANH_MUC WHERE DM_ten = 'Luật Lao động' LIMIT 1), (SELECT LTLPL_id FROM LOAI_TAI_LIEU_PHAP_LY WHERE LTLPL_ten = 'Nghị định' LIMIT 1), 'Nghị định 38/2022/NĐ-CP quy định mức lương tối thiểu', 'documents/lao-dong/nghi-đinh-382022nđ-cp-quy-đinh-muc-luong-toi-thieu.docx', 'docx', 'crawler', NOW(), '2022-06-12', FALSE, 'NOI_BO', '38/2022/NĐ-CP') ON DUPLICATE KEY UPDATE DM_id = VALUES(DM_id), LTLPL_id = VALUES(LTLPL_id), TL_duongDan = VALUES(TL_duongDan), TL_dinhDang = VALUES(TL_dinhDang), TL_ngayBanHanh = VALUES(TL_ngayBanHanh), TL_daXoa = VALUES(TL_daXoa);
